### ISSUE TITLE
Payee and memo are empty often

### ISSUE THREAD

**Issue by ericdevries** [DanielsWrath/YNABGoingDutch-ABN-edition#2]
Importing a TXT file into the app creates a CSV where often, both payee and memo are empty, making it difficult to categorize these transactions. 

Example input:

```
123456789	EUR	20200102	3481,68	4019,58	20200102	537,90	SEPA Overboeking                 IBAN: NL51RABO0317315722        BIC: RABONL2U                    Naam: SVB Breda                 Omschrijving: KINDERBIJSLAG 4e k wart. 19 PF12345678 WWW.SVB.NL Sociale Verzekeringsbank Breda    Kenmerk: PF11234123125132                                                                
123456789	EUR	20200102	4019,58	3481,68	20200102	-537,90	SEPA Overboeking                 IBAN: NL53ABNA0123456798        BIC: ABNANL2A                    Naam: Anoniem                   
123456789	EUR	20200102	3481,68	3479,68	20200102	-2,00	BEA   NR:NB0405   02.01.20/10.27 Hema Papendrecht,PAS536         PAPENDRECHT                                                      
123456789	EUR	20200103	3479,68	3449,69	20200103	-29,99	SEPA Incasso algemeen doorlopend Incassant: NL47ZZZ370924590000  Naam: Basic Fit Nederland B.V.   Machtiging: 123456789           Omschrijving: 05-01-2020 / 01-02 -2020                           IBAN: NL24RABO0168476207         Kenmerk: NO123456789-96         
123456789	EUR	20200103	3449,69	3316,61	20200103	-133,08	Maandpremie januari 2020         van verzekering 123456789       

``` 

Output:
```

Date | Payee | Category | Memo | Outflow | Inflow
-- | -- | -- | -- | -- | --
2020-01-02 |   |   |   | 0 | 537.90
2020-01-02 |   |   |   | 537.90 | 0
2020-01-02 | Hema Papendrecht |   |   | 2.00 | 0
2020-01-03 |   |   |   | 29.99 | 0
2020-01-03 |   |   |   | 133.08 | 0

```

**Comment by DanielsWrath** [comment]
What bank are you using?

**Comment by ericdevries** [comment]
I’m using ABN AMRO

**Comment by DanielHaitink** [comment]
Could you maybe send the file (or parts of it) to me? I cannot get any output when I put the Example input in a file.
You can anonymize everything, as long as it gives the same result.
My email is in my profile.

**Comment by ericdevries** [comment]
The extract is from the file, maybe it got trimmed or something. I’ll send
you a raw anonymous file tomorrow

**Comment by zigmob** [comment]
Hi guys, I am experiencing the same issue as Eric describes with ABN. Are there any updates on this matter? Thanks!

**Comment by ericdevries** [comment]
I completely forgot to send this file extract due to holidays back in july, so I expect no progress has been made

**Comment by DanielHaitink** [comment]
Like @ericdevries said, I have gotten no file so I was not able to fix anything. If either one of you can upload/send an anonymized TAB file in which the error occurs, I can fix it in a (few) day(s)

**Comment by zigmob** [comment]
Hi guys, thanks for your quick reaction!  I have send you an example file @DanielsWrath .

**Comment by DanielHaitink** [comment]
Should be fixed now! Please check if it works for you @zigmob @ericdevries

**Comment by zigmob** [comment]
Hi Daniel,

Thanks! Great improvement, just a few lines with empty "payee" left. I will
send you an example.

Wouter

**Comment by DanielHaitink** [comment]
Fixed in most recent release

**Comment by zigmob** [comment]
Great, works flawless, thanks for your efforts!
