### ISSUE TITLE
Inlezen van bankafschriften werkt niet meer 

### ISSUE THREAD

**Issue by Laradagio** [DanielsWrath/YNABGoingDutch-ABN-edition#9]
Het inlezen van bankafschriften van ABN AMRO werkt niet meer

Ik maak van de bankafschriften TXT bestanden en van bv 4 leest hij er maar 3 in. Dit had ik een week eerder ook en toen las het programma een ander bankafschrift in en de andere niet. (Gaat dus niet om hetzelfde bankrekeningnummer)

Kan dit worden opgelost?

Programma zegt dat er geen bestand is gekozen bij het bankafschrift wat niet wordt ingelezen.

Windows 11, Microsoft Edge versie 100.0.1185.39 (Officiële build) (64-bits)

Mijn engels is niet zo goed dus maar even in het nederlands geschreven.

**Comment by DanielHaitink** [comment]
> Het inlezen van bankafschriften van ABN AMRO werkt niet meer
> 
> Ik maak van de bankafschriften TXT bestanden en van bv 4 leest hij er maar 3 in. Dit had ik een week eerder ook en toen las het programma een ander bankafschrift in en de andere niet. (Gaat dus niet om hetzelfde bankrekeningnummer)

Bedoel je dat hij niet alle regels inleest? 
Zou je een voorbeeld bestand kunnen maken waar dit probleem zich voordoet en waarbij je de waarden anonimiseert? Je kan dat bestand toevoegen in de issue, maar je mag het ook mailen naar mij (zie mijn profiel voor mailadres)

> Programma zegt dat er geen bestand is gekozen bij het bankafschrift wat niet wordt ingelezen.

Of bedoel je dat het hele bestand niet wordt gelezen? Wat voor soort rekening is het? 

> Mijn engels is niet zo goed dus maar even in het nederlands geschreven. 

Geen probleem hoor

**Comment by DanielHaitink** [comment]
Fixed issue with latest commit.

**Comment by Laradagio** [comment]
You helped me three years ago, and I hope you can do it again.

Due to personal circumstances, I haven't used YNAB for months.

I just imported two files, and everything works fine.

With the third, I get the error message below. Could you please check what's wrong with this one?

 

The files that worked and those that didn't work are attached.
